# Generated by Django 4.2.5 on 2023-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
