# Generated by Django 4.2.5 on 2023-11-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ethereum_account',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
