# Generated by Django 4.2.5 on 2023-12-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_ethereum_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='NewUser',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
