# Generated by Django 4.2.5 on 2023-11-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_name_doctor_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
