# Generated by Django 4.2.5 on 2023-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
